apiVersion: v1                             # This defines the API version of the Kubernetes object
kind: Service                              # We're creating a Service to expose our app

metadata:
  name: {{ include "demo-app.fullname" . }}  # Dynamically generate the full name using a helper template
  labels:
    {{- include "demo-app.labels" . | nindent 4 }}  # Apply standardized labels from helper templates

spec:
  type: {{ .Values.service.type }}          # The type of service (ClusterIP, NodePort, LoadBalancer) is set from values.yaml
  ports:
    - port: {{ .Values.service.port }}      # This is the service's exposed port (e.g., 80), configurable in values.yaml
      targetPort: 80                        # This is the internal port on the container that traffic is forwarded to
  selector:
    {{- include "demo-app.selectorLabels" . | nindent 4 }}  # Select the Pods to route traffic to using defined label selectors
